name: Laravel CI/CD

on:
  push:
    branches:
      - main

jobs:

  tests:
    name: Run Tests
    runs-on: ubuntu-latest

    env:
      APP_ENV: testing

  
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: pdo_pgsql, zip, bcmath, opcache
          coverage: none

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Prepare Laravel
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run Tests
        run: php artisan test

  build-image:
    name: Build & Push Docker Image
    needs: tests
    runs-on: self-hosted
    outputs:
      NEW_VERSION: ${{ steps.version.outputs.version }}

    env:
      DOCKER_BUILDKIT: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Version
        id: version
        uses: paulhatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"
          major_pattern: "major:"
          minor_pattern: "feat:"

      - name: Set Variables
        run: |
          echo "NEW_VERSION=${{ steps.version.outputs.version }}" >> $GITHUB_ENV
          echo "DOCKER_CONTAINER=${{ secrets.DOCKER_CONTAINER }}" >> $GITHUB_ENV

      - name: Docker Login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
          -u "${{ secrets.DOCKER_USER }}" \
          --password-stdin

      - name: Build Docker Image
        run: |
          docker build \
            -t "$DOCKER_CONTAINER:$NEW_VERSION" \
            -t "$DOCKER_CONTAINER:latest" .

      - name: Push Docker Image
        run: |
          docker push "$DOCKER_CONTAINER:$NEW_VERSION"
          docker push "$DOCKER_CONTAINER:latest"

      - name: Docker Logout
        run: docker logout
  deploy:
    needs: build-image
    runs-on: self-hosted
    environment: 
          name: prod
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate ENV
        run: |
          cp .env.template .env

          sed -i -r 's/APP_NAME\=(.*)/APP_NAME="${{ vars.APP_NAME }}"/g' .env
          sed -i -r 's/APP_ENV\=(.*)/APP_ENV="${{ vars.APP_ENV }}"/g' .env
          sed -i -r 's/APP_KEY\=(.*)/APP_KEY="${{ secrets.APP_KEY }}"/g' .env
          sed -i -r 's/APP_DEBUG\=(.*)/APP_DEBUG="${{ vars.APP_DEBUG }}"/g' .env
          sed -i -r 's/APP_URL\=(.*)/APP_URL="${{ vars.APP_URL }}"/g' .env
          sed -i -r 's/DB_CONNECTION\=(.*)/DB_CONNECTION="${{ vars.DB_CONNECTION }}"/g' .env
          sed -i -r 's/DB_HOST\=(.*)/DB_HOST="${{ secrets.DB_HOST }}"/g' .env
          sed -i -r 's/DB_PORT\=(.*)/DB_PORT="${{ secrets.DB_PORT }}"/g' .env
          sed -i -r 's/DB_DATABASE\=(.*)/DB_DATABASE="${{ secrets.DB_DATABASE }}"/g' .env
          sed -i -r 's/DB_USERNAME\=(.*)/DB_USERNAME="${{ secrets.DB_USERNAME }}"/g' .env
          sed -i -r 's/DB_PASSWORD\=(.*)/DB_PASSWORD="${{ secrets.DB_PASSWORD }}"/g' .env

          echo "===== GENERATED ENV ====="
          cat .env
      
      - name: Docker Login
        run: | 
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
          -u "${{ secrets.DOCKER_USER }}" \
          --password-stdin

      - name: Copy deployment files 
        run: | 
          mkdir -p ~/apps/laravel-app 
          cp docker-compose.yml ~/apps/laravel-app/ 
          cp .env ~/apps/laravel-app/

      - name: Set Variables Deploy
        run: |
          echo "NEW_VERSION=${{ needs.build-image.outputs.NEW_VERSION }}" >> $GITHUB_ENV
          echo "DOCKER_CONTAINER=${{ secrets.DOCKER_CONTAINER }}" >> $GITHUB_ENV
      
      - name: Deploy containers 
        run: | 
          cd ~/apps/laravel-app
          docker pull "$DOCKER_CONTAINER:$NEW_VERSION"
          docker compose down && docker compose up -d

      - name: Laravel Optimize 
        run: |
          docker compose exec -T app php artisan optimize

      - name: Run Migrations 
        run: | 
          docker compose exec -T app php artisan migrate --force  

      - name: Clear Cache 
        run: | 
          docker compose exec -T app php artisan cache:clear && \
          docker compose exec -T app php artisan config:clear && \
          docker compose exec -T app php artisan route:clear && \
          docker compose exec -T app php artisan view:clear

      - name: Docker Logout
        run: docker logout
